ARC_ArsenalCategoryConfig {
 m_aCategories {
  ARC_ArsenalCategory "{ADE03F261EB52934}" {
   m_sName "Submachine Guns"
   m_sIcon "{71648F15B3984B87}UI/Textures/Editor/Attributes/Arsenal/Attribute_Arsenal_AssaultRifles.edds"
   m_eItemTypes 2
   m_eItemModes 12
   m_aPrefabContains {
    "smg" "_mp5" "mpx" "ump" "vityaz" "pp19" "pp2000" "ppsh" "uzi" "vector" "p90" "mp7" "kedr" "bizon"
   }
  }
  ARC_ArsenalCategory "{162B891156372C8F}" {
   m_sName "Assault Rifles"
   m_sIcon "{71648F15B3984B87}UI/Textures/Editor/Attributes/Arsenal/Attribute_Arsenal_AssaultRifles.edds"
   m_eItemTypes 2
   m_eItemModes 12
  }
  ARC_ArsenalCategory "{E4447E1967D19A06}" {
   m_sName "Sniper Rifles"
   m_sIcon "{A2B4C0BFBECE6400}UI/Textures/Editor/Attributes/Arsenal/Attribute_Arsenal_SniperRifles.edds"
   m_eItemTypes 256
   m_eItemModes 12
  }
  ARC_ArsenalCategory "{E95A8B2E2869478E}" {
   m_sName "Machine Guns"
   m_sIcon "{A02EB3B80E276400}UI/Textures/Editor/Attributes/Arsenal/Attribute_Arsenal_MachineGuns.edds"
   m_eItemTypes 32
   m_eItemModes 12
  }
  ARC_ArsenalCategory "{38912E06B519BBBC}" {
   m_sName "Pistols"
   m_sIcon "{2EEBBBCA36DD775F}UI/Textures/Editor/Attributes/Arsenal/Attribute_Arsenal_Pistols.edds"
   m_eItemTypes 4
   m_eItemModes 12
  }
  ARC_ArsenalCategory "{2D2B04B409410306}" {
   m_sName "Launchers"
   m_sIcon "{10840233D666C940}UI/Textures/Editor/Attributes/Arsenal/Attribute_Arsenal_Launcher.edds"
   m_eItemTypes 1048592
   m_eItemModes 12
  }
  ARC_ArsenalCategory "{0861C5391F8D16A7}" {
   m_sName "Ammunition"
   m_sIcon "{A3D157619860A564}UI/Textures/Editor/Attributes/Arsenal/Attribute_Arsenal_Magazines.edds"
   m_eItemModes 16
  }
  ARC_ArsenalCategory "{F86305228EA5DB51}" {
   m_sName "Attachments"
   m_sIcon "{CB055708E982C0A5}UI/Textures/Editor/Attributes/Arsenal/Attribute_Arsenal_Optics.edds"
   m_eItemModes 64
  }
  ARC_ArsenalCategory "{ED6B555AAC6E563E}" {
   m_sName "Throwables"
   m_sIcon "{233A8BC0520B1B8B}UI/Textures/Editor/Attributes/Arsenal/Attribute_Arsenal_Grenades.edds"
   m_eItemTypes 520
  }
  ARC_ArsenalCategory "{CCD1F740309E9276}" {
   m_sName "Explosives"
   m_sIcon "{91C4A9B5AD80D443}UI/Textures/Editor/Attributes/Arsenal/Attribute_Arsenal_Explosive.edds"
   m_eItemTypes 262144
  }
  ARC_ArsenalCategory "{5B1E0C7A2D9F4E31}" {
   m_sName "Clothing"
   m_sIcon "{92245C15E122EDB2}UI/Textures/Editor/Attributes/Arsenal/Attribute_Arsenal_Jackets.edds"
   m_eItemTypes 551936
  }
  ARC_ArsenalCategory "{5B1E0C7A2D9F4E32}" {
   m_sName "Vests and Backpacks"
   m_sIcon "{2DCA69EEB8628C06}UI/Textures/Editor/Attributes/Arsenal/Attribute_Arsenal_Vests.edds"
   m_eItemTypes 36992
  }
  ARC_ArsenalCategory "{5B1E0C7A2D9F4E33}" {
   m_sName "Medical"
   m_sIcon "{CDF868B16669B7EA}UI/Textures/Editor/Attributes/Arsenal/Attribute_Arsenal_Medical.edds"
   m_eItemTypes 64
  }
  ARC_ArsenalCategory "{5B1E0C7A2D9F4E34}" {
   m_sName "Equipment"
   m_sIcon "{CDF94F179A33CFB9}UI/Textures/Editor/Attributes/Arsenal/Attribute_Arsenal_Accessories.edds"
   m_eItemTypes 65536
  }
 }
}
