ARC_ArsenalCategoryConfig {
 m_aCategories {
  ARC_ArsenalCategory "{ADE03F261EB52934}" {
   m_sName "Weapons"
   m_sIcon "{71648F15B3984B87}UI/Textures/Editor/Attributes/Arsenal/Attribute_Arsenal_AssaultRifles.edds"
   m_eItemTypes 1048886
   m_eItemModes 12
  }
  ARC_ArsenalCategory "{162B891156372C8F}" {
   m_sName "Ammunition"
   m_sIcon "{A3D157619860A564}UI/Textures/Editor/Attributes/Arsenal/Attribute_Arsenal_Magazines.edds"
   m_eItemModes 16
  }
  ARC_ArsenalCategory "{E4447E1967D19A06}" {
   m_sName "Attachments"
   m_sIcon "{CB055708E982C0A5}UI/Textures/Editor/Attributes/Arsenal/Attribute_Arsenal_Optics.edds"
   m_eItemModes 64
  }
  ARC_ArsenalCategory "{E95A8B2E2869478E}" {
   m_sName "Throwables and Explosives"
   m_sIcon "{233A8BC0520B1B8B}UI/Textures/Editor/Attributes/Arsenal/Attribute_Arsenal_Grenades.edds"
   m_eItemTypes 262664
  }
  ARC_ArsenalCategory "{38912E06B519BBBC}" {
   m_sName "Clothing"
   m_sIcon "{92245C15E122EDB2}UI/Textures/Editor/Attributes/Arsenal/Attribute_Arsenal_Jackets.edds"
   m_eItemTypes 551936
  }
  ARC_ArsenalCategory "{2D2B04B409410306}" {
   m_sName "Vests and Backpacks"
   m_sIcon "{2DCA69EEB8628C06}UI/Textures/Editor/Attributes/Arsenal/Attribute_Arsenal_Vests.edds"
   m_eItemTypes 36992
  }
  ARC_ArsenalCategory "{0861C5391F8D16A7}" {
   m_sName "Medical"
   m_sIcon "{CDF868B16669B7EA}UI/Textures/Editor/Attributes/Arsenal/Attribute_Arsenal_Medical.edds"
   m_eItemTypes 64
  }
  ARC_ArsenalCategory "{F86305228EA5DB51}" {
   m_sName "Equipment"
   m_sIcon "{CDF94F179A33CFB9}UI/Textures/Editor/Attributes/Arsenal/Attribute_Arsenal_Accessories.edds"
   m_eItemTypes 65536
   m_eItemModes 34
  }
 }
}
