ARC_ArsenalCategoryConfig {
 m_aCategories {
  ARC_ArsenalCategory "{ADE03F261EB52934}" {
   m_sName "Submachine Guns"
   m_eItemTypes 2
   m_eItemModes 12
   m_aPrefabContains {
    "smg" "_mp5" "mpx" "ump" "vityaz" "pp19" "pp2000" "ppsh" "uzi" "vector" "p90" "mp7" "kedr" "bizon"
   }
  }
  ARC_ArsenalCategory "{162B891156372C8F}" {
   m_sName "Assault Rifles"
   m_eItemTypes 2
   m_eItemModes 12
  }
  ARC_ArsenalCategory "{E4447E1967D19A06}" {
   m_sName "Sniper Rifles"
   m_eItemTypes 256
   m_eItemModes 12
  }
  ARC_ArsenalCategory "{E95A8B2E2869478E}" {
   m_sName "Machine Guns"
   m_eItemTypes 32
   m_eItemModes 12
  }
  ARC_ArsenalCategory "{38912E06B519BBBC}" {
   m_sName "Pistols"
   m_eItemTypes 4
   m_eItemModes 12
  }
  ARC_ArsenalCategory "{2D2B04B409410306}" {
   m_sName "Launchers"
   m_eItemTypes 1048592
   m_eItemModes 12
  }
  ARC_ArsenalCategory "{0861C5391F8D16A7}" {
   m_sName "Ammunition"
   m_eItemModes 16
  }
  ARC_ArsenalCategory "{F86305228EA5DB51}" {
   m_sName "Attachments"
   m_eItemModes 64
  }
  ARC_ArsenalCategory "{ED6B555AAC6E563E}" {
   m_sName "Throwables"
   m_eItemTypes 520
  }
  ARC_ArsenalCategory "{CCD1F740309E9276}" {
   m_sName "Explosives"
   m_eItemTypes 262144
  }
  ARC_ArsenalCategory "{5B1E0C7A2D9F4E31}" {
   m_sName "Clothing"
   m_eItemTypes 551936
  }
  ARC_ArsenalCategory "{5B1E0C7A2D9F4E32}" {
   m_sName "Vests and Backpacks"
   m_eItemTypes 36992
  }
  ARC_ArsenalCategory "{5B1E0C7A2D9F4E33}" {
   m_sName "Medical"
   m_eItemTypes 64
  }
  ARC_ArsenalCategory "{5B1E0C7A2D9F4E34}" {
   m_sName "Equipment"
   m_eItemTypes 65536
  }
 }
}
